name: Email Approval Workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [opened]
  workflow_dispatch:

jobs:
  approve_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Approval Email
        uses: macnev2013/manual-approval@v1.0.18  
        with:
          approvers: madhurgoel2116
          secret: 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
          minimum-approvals: 1

  build-dotnet-app:
    needs: [approve_email]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /home/runner/work/app-dotnet/app-dotnet/bin/Release/net6.0

  download-artifact:
    runs-on: self-hosted
    needs: build-dotnet-app
    steps: 
      - name: Stop IIS site
        run: IISReset /stop
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: D:\app-dotnet\app-dotnet\wwwroot\gh-actions-website.com
      - name: Start IIS Site
        run: IISReset /start
