name: Email Approval Workflow

on:
 push:
   branches: [ "main" ]
 pull_request:
    branches: [ "main" ]
 # email:
 #    types: [opened]
 workflow_dispatch:

jobs:
  approve_email:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Check if email is from approved user
        id: approve_check
        run: |
          if [[ "mgoel3900@gmail.com" == "madhurgoel2116" ]]; then
            echo "::madhurgoel41=approved::true"
          else
            echo "::madhurgoel41=approved::false"
          fi
          
  build-dotnet-app:
    needs: [approve_email]
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # - name: Publish
      #   run: dotnet publish -c Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /home/runner/work/app-dotnet/app-dotnet/bin/Release/net6.0
          # if-no-files-found: error
          
  download-artifact:
    runs-on: self-hosted
    needs: build-dotnet-app
    
    steps: 
    - name: stop IIS site
      run: |
       IISReset /stop
        
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: D:\app-dotnet\app-dotnet\wwwroot\gh-actions-website.com
        
    - name: Start IIS Site
      run: |
       IISReset /start
