name: Email Approval Workflow
on:
  push:
    branches: main
  pull_request:
    branches: none # [main]
  workflow_dispatch:

jobs:       
 build-dotnet-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-dotnet
    steps:
      - uses: trstringer/manual-approval@v1.9.0
        with:
          secret: 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
          approvers: madhurgoel41,madhurgoel2116
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          
      # - name: Checkout code
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /home/runner/work/app-dotnet/app-dotnet/bin/Release/net6.0/publish

 download-artifact:
    runs-on: self-hosted
    needs: build-dotnet-app
    steps:
      - name: Stop IIS site
        run: IISReset /stop
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: D:\app-dotnet\app-dotnet\wwwroot\gh-actions-website.com
      - name: Start IIS Site
        run: IISReset /start
