name: .Net
on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
      
jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # - name: Publish
      #   run: dotnet publish -c Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /home/runner/work/app-dotnet/app-dotnet/bin/Release/net6.0/publish
          # if-no-files-found: error
          
  download-artifact:
    runs-on: self-hosted
    needs: build-dotnet-app
    
    steps: 
    - name: stop IIS site
      run: |
       IISReset MADHOR GOEL /stop
        
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: D:\app-dotnet\app-dotnet\wwwroot\gh-actions-website.com
        
    - name: Start IIS Site
      run: |
       IISReset MADHOR GOEL /start
    


              
        
         
              
          
       
